services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    networks:
      - app-softdev

networks:
  app-softdev:
    driver: bridge
    external: true